use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:iscodecheng/RCPrivatePods.git'

platform :ios, '10.0'

target 'RCBaseLib_Example' do
  pod 'RCBaseLib', :path => '../'

  target 'RCBaseLib_Tests' do
    inherit! :search_paths

    
    
  end
end
